networks:
  naucto-dev:
    driver: bridge
    name: naucto-dev
    attachable: true

services:
  db:
    networks:
      - naucto-dev

  backend:
    build:
      target: dev
    networks:
      - naucto-dev
