networks:
  naucto-dev:
    name: naucto-dev
    driver: bridge

services:
  db:
    networks:
      - naucto-dev

  backend:
    build:
      target: dev
    networks:
      - naucto-dev
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src

        - action: sync
          path: ./prisma
          target: /app/prisma
          ignore:
            - prisma/migrations

        - action: rebuild
          path: package.json

        - action: rebuild
          path: prisma/schema.prisma

